[package]
name = "ecl"
version = "0.1.0"
authors = ["Kevin Cox <kevincox@kevincox.ca>"]

[dependencies]
lazy_static = "0.2"
peg = "0.3"
ramp = "0.3"
regex = "0.1"
serde = "0.8"
serde_json = "0.8"

[dev-dependencies]
difference = "0.4"
